# Parameters for maskAL
# python maskAL.py --config active_learning/config/maskAL.yaml
# explanation can be found here: https://git.wur.nl/blok012/maskAL

# folders
weightsroot: "./weights"
resultsroot: "./results"
dataroot: "./datasets/exp1/repeat_factor_training_sampler_2"
traindir: "./datasets/train"
valdir: "./datasets/val"
testdir: "./datasets/test"

# training-parameters
cuda_visible_devices: '1'
classes: ['healthy', 'damaged', 'matured', 'cateye', 'headrot']
transfer_learning_on_previous_models: False
train_complete_trainset: True
duplicate_initial_model: False
learning_rate: 0.01
warmup_iterations: 1000
max_iterations: 50000
steps: [30000, 45000]
eval_period: 500
weight_decay: 0.0001
learning_policy: 'steps_with_decay'
gamma: 0.1
train_batch_size: 1
num_workers: 2

# train-sampler
train_sampler: "RepeatFactorTrainingSampler"
minority_classes: ['damaged', 'matured', 'cateye', 'headrot']
oversample_factor: 2

# evaluation-parameters
confidence_threshold: 0.5
nms_threshold: 0.01

# active-learning sampling
experiment_name: 'exp1/repeat_factor_training_sampler_2'
strategies: ['uncertainty', 'random', 'certainty']
mode: ['min', ' ', 'mean']
initial_datasize: 100
pool_size: 200
loops: 12
dropout_probability: 0.5
iterations: 5
al_batch_size: 5
iou_thres: 0.5
