# Parameters for maskAL
# python maskAL.py --config active_learning/config/maskAL.yaml
# explanation can be found here: https://git.wur.nl/blok012/maskAL

# folders
weightsroot: "./weights"
resultsroot: "./results"
dataroot: "./datasets"
traindir: "./datasets/train"
valdir: "./datasets/val"
testdir: "./datasets/test"

# training-parameters
cuda_visible_devices: '0'
classes: ['healthy', 'damaged', 'matured', 'cateye', 'headrot']
transfer_learning_on_previous_models: True
train_complete_trainset: False
duplicate_initial_model: True

# active-learning sampling
experiment_name: 'exp1'
strategies: ['uncertainty', 'random', 'certainty']
mode: ['min', ' ', 'mean']
initial_datasize: 200
pool_size: 200
loops: 14
dropout_probability: 0.5
iterations: 5
batch_size: 5
iou_thres: 0.5
