# Parameters for maskAL
# python maskAL.py --config active_learning/config/maskAL.yaml
# explanation can be found here: https://git.wur.nl/blok012/maskAL

# folders
weightsroot: "./weights"
resultsroot: "./results"
dataroot: "./datasets"
traindir: "./datasets/train"
valdir: "./datasets/val"
testdir: "./datasets/test"

# training-parameters
cuda_visible_devices: '0'
classes: ['healthy', 'damaged', 'matured', 'cateye', 'headrot']
transfer_learning_on_previous_models: True
train_complete_trainset: False
duplicate_initial_model: True
learning_rate: 0.01
warmup_iterations: 1000
max_iterations: 5000
steps: [3000, 4500]
eval_period: 500
weight_decay: 0.0001
learning_policy: 'steps_with_decay'
gamma: 0.1
train_batch_size: 2
num_workers: 2

# evaluation-parameters
confidence_threshold: 0.5
nms_threshold: 0.01

# active-learning sampling
experiment_name: 'exp1'
strategies: ['uncertainty', 'random', 'certainty']
mode: ['min', ' ', 'mean']
initial_datasize: 200
pool_size: 200
loops: 14
dropout_probability: 0.5
iterations: 5
al_batch_size: 5
iou_thres: 0.5
