# Parameters for maskAL
# python maskAL.py --cfg active_learning/cfg/maskAL_broccoli.yaml
# explanation can be found here: https://git.wur.nl/blok012/maskAL

# folders
weightsroot: "./weights"
resultsroot: "./results"
dataroot: "./datasets"
traindir: "./datasets/train"
valdir: "./datasets/val"
testdir: "./datasets/test"

# training-parameters
classes: ['broccoli', 'damaged', 'matured', 'cateye', 'headrot']

# active-learning sampling
strategies: ['uncertainty', 'random', 'certainty']
initial_datasize: 100
pool_size: 50
loops: 18
iterations: 5
batch_size: 5
iou_thres: 0.5
