# Parameters for maskAL
# git revert 0552850
# python maskAL.py --config active_learning/config/maskAL_exp2_run2.yaml
# explanation can be found here: https://github.com/pieterblok/maskal

# folders
weightsroot: "./weights"
resultsroot: "./results"
dataroot: "./datasets/exp2/run2"
traindir: "./datasets/train"
valdir: "./datasets/val"
testdir: "./datasets/test02"

# training-parameters
cuda_visible_devices: '1'
classes: ['healthy', 'damaged', 'matured', 'cateye', 'headrot']
transfer_learning_on_previous_models: True
train_complete_trainset: False
duplicate_initial_model: True
learning_rate: 0.01
warmup_iterations: 500
train_iterations_base: 2500
train_iterations_step_size: 2500
step_image_number: 500
step_ratios: [0.5, 0.8]
eval_period: 500
checkpoint_period: -1
weight_decay: 0.0001
learning_policy: 'steps_with_decay'
gamma: 0.1
train_batch_size: 2
num_workers: 2

# train-sampler
train_sampler: "RepeatFactorTrainingSampler"
minority_classes: ['damaged', 'matured', 'cateye', 'headrot']
repeat_factor_smallest_class: 1.5

# evaluation-parameters
confidence_threshold: 0.5
nms_threshold: 0.01

# active-learning sampling
experiment_name: 'exp2/run2'
strategies: 'uncertainty'
mode: 'mean'
initial_datasize: 100
pool_size: [50, 100, 200, 400, [50, 100, 200], [100, 200, 400], [200, 400]]
equal_pool_size: [True, True, True, True, False, False, False]
loops: [48, 24, 12, 6, [8, 4, 8], [4, 2, 4], [4, 4]]
dropout_probability: 0.25
mcd_iterations: 20
dropout_method: 'head'
al_batch_size: 1
iou_thres: 0.5
resume: False
auto_annotate: False
export_format: labelme
supervisely_meta_json: "./datasets/meta.json"
