# Parameters for maskAL
# python maskAL.py --config active_learning/config/maskAL.yaml
# explanation can be found here: https://git.wur.nl/blok012/maskAL

# folders
weightsroot: "./weights"
resultsroot: "./results"
dataroot: "./datasets"
traindir: "./datasets/train"
valdir: "./datasets/val"
testdir: "./datasets/test"

# training-parameters
cuda_visible_devices: '0'
classes: ['broccoli', 'damaged', 'matured', 'cateye', 'headrot']
train_complete_trainset: False

# active-learning sampling
no_experiments: 1
strategies: ['uncertainty', 'random', 'certainty']
mode: ['min', ' ', 'max']
initial_datasize: 200
pool_size: 100
loops: 8
iterations: 5
batch_size: 5
iou_thres: 0.5
